import type { CockpitViewModel } from "../model/cockpit-view-model";

const accounting = [["total", "Total"], ["kept", "Kept"], ["dropped", "Dropped"], ["excluded", "Excluded"], ["unresolved", "Unresolved"]] as const;
const provenance = [["subjectRepository", "Subject repository"], ["subjectRevision", "Subject revision"], ["artifactRepository", "Artifact repository"], ["artifactRevision", "Artifact revision"], ["producerVersion", "Producer version"], ["algorithmVersion", "Algorithm version"], ["inputDigest", "Input digest"], ["artifactDigest", "Artifact digest"], ["dataHubReadParameters", "DataHub read parameters"], ["producerPath", "Producer path"], ["immutableSourceUrl", "Immutable source URL"], ["limitations", "Limitations"]] as const;

export function ReceiptsView({ model }: { model: CockpitViewModel }) {
  const receipt = model.receipt;
  return <div className="receipts-view">
    <section aria-labelledby="accounting-title"><p className="eyebrow">Resolution accounting</p><h2 id="accounting-title">Resolution remains bounded by the pinned manifest</h2><table className="accounting-table"><caption>No count alone implies completeness.</caption><thead><tr>{accounting.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody><tr>{accounting.map(([key]) => <td key={key}>{receipt.accounting[key]}</td>)}</tr></tbody></table><section aria-labelledby="unresolved-title"><h3 id="unresolved-title">Named unresolved items ({receipt.accounting.unresolved})</h3><ul>{receipt.unresolvedItems.map((item) => <li key={item}>{item}</li>)}</ul></section></section>
    <section aria-labelledby="provenance-title"><p className="eyebrow">Provenance</p><h2 id="provenance-title">Source and epistemic state are separate</h2><p><span className="source-tag">{receipt.provenance.source}</span> Read: {model.read} · Completeness: {model.completeness === "complete-against-pinned-manifest" ? "Complete against pinned manifest" : "Not established"}</p><dl className="provenance-list">{provenance.map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{receipt.provenance[key]}</dd></div>)}</dl><a href={model.immutableViewSourceUrl}>View immutable source</a></section>
    <section aria-labelledby="writeback-title"><p className="eyebrow">Writeback proof</p><h2 id="writeback-title">Terminal disposition is not inferred</h2><dl className="provenance-list"><div><dt>Intent</dt><dd>{receipt.writeback.intent}</dd></div><div><dt>Before-state read</dt><dd>{receipt.writeback.beforeState}</dd></div><div><dt>Mutation response</dt><dd>{receipt.writeback.mutationResponse}</dd></div><div><dt>After-state read</dt><dd>{receipt.writeback.afterStateRead} · {receipt.writeback.afterStateFreshness}</dd></div><div><dt>Both states read</dt><dd>{String(receipt.writeback.bothStatesRead)}</dd></div><div><dt>Intended-state observation</dt><dd>{receipt.writeback.intendedStateObservation}</dd></div><div><dt>Terminal disposition</dt><dd>{receipt.writeback.terminalDisposition}</dd></div></dl>{receipt.writeback.terminalDisposition === "accepted-not-observed" && <p role="note">Accepted mutation is not success until intended state is observed.</p>}</section>
    <section aria-labelledby="disclosure-title"><p className="eyebrow">Evaluation and disclosure</p><h2 id="disclosure-title">Limitations lead</h2><p>{receipt.evaluation.limitations}</p><dl className="provenance-list"><div><dt>Paired evaluation spread</dt><dd>{receipt.evaluation.pairedSpread}</dd></div><div><dt>LOC baseline</dt><dd>{receipt.evaluation.locBaseline}</dd></div></dl><details><summary>Raw evidence receipt</summary><pre>{receipt.evaluation.rawEvidence}</pre><button type="button" disabled>Copy raw receipt (available after HAC-226 binding)</button><button type="button" disabled>Download receipt (available after HAC-226 binding)</button></details></section>
  </div>;
}
