/**
 * HAC-152 paired external-model runner.
 *
 * The model is invoked twice, once with the DataHub projection and once with
 * the projection plus corpus-matched workspace evidence.  The task prompt,
 * model, and decoding settings are identical.  The context envelope is the
 * only varying input; it is deliberately kept separate from the task prompt
 * so the prompt digest remains a meaningful comparison control.
 */

import {
  JUDGE_RUN_BUNDLE_VERSION,
  PLAN_COMPARISON_VERSION,
  digestEvent,
  type JudgeRunBundle,
  type Plan,
  type PlanDelta,
  type RunIdentity,
} from "./plan-comparison.js";
import { toDataHubOnly, type ChangeImpactEvent } from "./change-impact-event.js";

export interface ModelPlanResponse {
  steps: Array<{ id: string; action: string }>;
}

/** The caller owns transport/authentication; this keeps credentials out of artifacts. */
export type PlanInvoker = (request: {
  mode: "datahub-only" | "joined";
  taskPrompt: string;
  context: ChangeImpactEvent;
  run: RunIdentity;
}) => Promise<ModelPlanResponse>;

export interface PairedRunInput {
  event: ChangeImpactEvent;
  run: RunIdentity;
  /** Exact change request, hashed into `run.promptDigest` by the CLI. */
  taskPrompt: string;
  invoke: PlanInvoker;
}

const requireCorpus = (event: ChangeImpactEvent): { repository: string; revision: string; source: string } => {
  const { repository, commit } = event.provenance.corpus;
  const source = event.code.repositoryRelativePath;
  if (repository === null || commit === null || source === null || event.provenance.workspaceArtifact?.integrity !== "exact-match") {
    throw new Error("A paired plan run requires an exact corpus-matched repository, revision, and repository-relative source path.");
  }
  return { repository, revision: commit, source };
};

const asPlan = (mode: Plan["mode"], run: RunIdentity, response: ModelPlanResponse): Plan => ({
  mode,
  run,
  steps: response.steps.map((step) => ({ id: step.id.trim(), action: step.action.trim() })),
});

const planText = (plan: Plan) => plan.steps.map((step) => step.action).join("\n").toLowerCase();

const containsExact = (plan: Plan, text: string) => planText(plan).includes(text.toLowerCase());

function assertConditionOutputs(datahubOnly: Plan, joined: Plan, source: string, revision: string): void {
  const datahubText = planText(datahubOnly);
  if (!/\b(refuse|cannot|can't|do not)\b/.test(datahubText) || !/\b(unknown|not established|not known|unavailable)\b/.test(datahubText)) {
    throw new Error("DataHub-only model output must explicitly refuse the unknown source location.");
  }
  if (containsExact(datahubOnly, source)) {
    throw new Error("DataHub-only model output leaked or guessed the joined repository-relative source path.");
  }
  if (!containsExact(joined, source) || !containsExact(joined, revision)) {
    throw new Error("Joined model output must use the exact repository-relative source and pinned revision.");
  }
}

/**
 * Build only deltas which are directly demonstrated by the two model outputs.
 * Their reasons and evidence references are generated by the harness, not
 * invented by the model, so a malformed response cannot manufacture support.
 */
function deriveDeltas(datahubOnly: Plan, joined: Plan, source: string, revision: string): PlanDelta[] {
  const deltas: PlanDelta[] = [];
  if (!containsExact(datahubOnly, source) && containsExact(joined, source)) {
    deltas.push({
      kind: "added",
      label: `use exact source ${source}`,
      reason: "Only the joined context contains the corpus-matched repository-relative producing file.",
      evidenceRefs: ["evidence.records[0]"],
    });
  }
  if (/\b(refuse|cannot|can't|do not)\b/.test(planText(datahubOnly)) && !/\b(refuse|cannot|can't|do not)\b/.test(planText(joined))) {
    deltas.push({
      kind: "removed",
      label: "refuse unknown source location",
      reason: "The DataHub-only projection records that repository-relative source location is not exposed; joined evidence resolves it exactly.",
      evidenceRefs: ["unavailable[\"code.repositoryRelativePath\"]", "evidence.records[0]"],
    });
  }
  if (containsExact(joined, source) && containsExact(joined, revision)) {
    deltas.push({
      kind: "constrained",
      label: `constrain work to ${source} at ${revision}`,
      reason: "The exact corpus revision and producing file constrain the joined plan to one checkable source location.",
      evidenceRefs: ["evidence.records[0]"],
    });
  }
  return deltas;
}

/** Invoke the selected model under both conditions and bind its outputs to one event. */
export async function runPairedPlan({ event, run, taskPrompt, invoke }: PairedRunInput): Promise<JudgeRunBundle> {
  const { repository, revision, source } = requireCorpus(event);
  const datahubOnlyEvent = toDataHubOnly(event);
  const [datahubOnlyResponse, joinedResponse] = await Promise.all([
    invoke({ mode: "datahub-only", taskPrompt, context: datahubOnlyEvent, run }),
    invoke({ mode: "joined", taskPrompt, context: event, run }),
  ]);
  const datahubOnlyPlan = asPlan("datahub-only", run, datahubOnlyResponse);
  const joinedPlan = asPlan("joined", run, joinedResponse);
  assertConditionOutputs(datahubOnlyPlan, joinedPlan, source, revision);
  const deltas = deriveDeltas(datahubOnlyPlan, joinedPlan, source, revision);
  if (deltas.length === 0) throw new Error("The paired model invocation produced no evidence-backed semantic delta.");

  return {
    bundleVersion: JUDGE_RUN_BUNDLE_VERSION,
    event,
    comparison: {
      artifactVersion: PLAN_COMPARISON_VERSION,
      eventDigest: digestEvent(event),
      snapshot: { repository, revision, datahub: { gmsUrl: event.provenance.datahub.gmsUrl, eventProducedAt: event.provenance.producedAt } },
      datahubOnlyPlan,
      joinedPlan,
      deltas,
    },
  };
}
